# This file was generated by GoReleaser. DO NOT EDIT.
cask "pg_hardstorage" do
  version "1.3.3"

  on_macos do
    on_arm do
      sha256 "a137efda3be33db84e9f598a28e9d8fef3388ecac73bd11f9aa07a0519f136d0"
      url "https://github.com/cybertec-postgresql/pg_hardstorage/releases/download/v#{version}/pg_hardstorage_#{version}_darwin_arm64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0d48fbe1dbc6bacf1e9db4b25110d1632580b2ed6ef19a4c050b717c26350f3d"
      url "https://github.com/cybertec-postgresql/pg_hardstorage/releases/download/v#{version}/pg_hardstorage_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "269ac7589da434f61dff2f2da00e00db732679a50a98d1ba389d49b767acc71d"
      url "https://github.com/cybertec-postgresql/pg_hardstorage/releases/download/v#{version}/pg_hardstorage_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pg_hardstorage"
  desc "PostgreSQL backup, done right — agent + CLI with continuous WAL streaming, content-addressed dedup, envelope encryption, and signed manifests."
  homepage "https://github.com/cybertec-postgresql/pg_hardstorage"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pg_hardstorage"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/pg_hardstorage"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    pg_hardstorage connects to PostgreSQL over the replication protocol
    and needs no local PostgreSQL server. If you want the psql client
    locally, install it separately:
      brew install libpq           # client only
      brew install postgresql@18   # full server

    Docs: https://docs.pghardstorage.org
  EOS
end
