# This file was generated by GoReleaser. DO NOT EDIT.
cask "pg_hardstorage" do
  version "1.2.4"

  on_macos do
    on_arm do
      sha256 "deaaa6ffc25f90758322a1b8a9b0d4a7f0d681e6f5ae2e14d6e3aae5b5783037"
      url "https://github.com/cybertec-postgresql/pg_hardstorage/releases/download/v#{version}/pg_hardstorage_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c09f31cf03802daeea7e150ead901f7234fb7f45f8eb0dc82b855ad3c3a6585a"
      url "https://github.com/cybertec-postgresql/pg_hardstorage/releases/download/v#{version}/pg_hardstorage_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a27da80cfc4bd163c3f41c5e15252a84b18024a091d5b1e08c8c930eadf38d51"
      url "https://github.com/cybertec-postgresql/pg_hardstorage/releases/download/v#{version}/pg_hardstorage_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pg_hardstorage"
  desc "PostgreSQL backup, done right — agent + CLI with continuous WAL streaming, content-addressed dedup, envelope encryption, and signed manifests."
  homepage "https://github.com/cybertec-postgresql/pg_hardstorage"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pg_hardstorage"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/pg_hardstorage"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    pg_hardstorage connects to PostgreSQL over the replication protocol
    and needs no local PostgreSQL server. If you want the psql client
    locally, install it separately:
      brew install libpq           # client only
      brew install postgresql@18   # full server

    Docs: https://docs.pghardstorage.org
  EOS
end
