# This file was generated by GoReleaser. DO NOT EDIT.
cask "pg_hardstorage" do
  version "1.4.1"

  on_macos do
    on_arm do
      sha256 "f30bcf7e846b7be8ecba1a08e1c2036f949c0b0cbdd65b8d2e4fb0b3720c0c01"
      url "https://github.com/cybertec-postgresql/pg_hardstorage/releases/download/v#{version}/pg_hardstorage_#{version}_darwin_arm64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6eb88972b9261daef7bcded137cc63066bba0336a4a6c230c2fae5e54905dcfd"
      url "https://github.com/cybertec-postgresql/pg_hardstorage/releases/download/v#{version}/pg_hardstorage_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "167febc7b22d2ba455be5145a634d4de87a7f25466cad49018777092590ab122"
      url "https://github.com/cybertec-postgresql/pg_hardstorage/releases/download/v#{version}/pg_hardstorage_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pg_hardstorage"
  desc "PostgreSQL backup, done right — agent + CLI with continuous WAL streaming, content-addressed dedup, envelope encryption, and signed manifests."
  homepage "https://github.com/cybertec-postgresql/pg_hardstorage"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pg_hardstorage"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/pg_hardstorage"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    pg_hardstorage connects to PostgreSQL over the replication protocol
    and needs no local PostgreSQL server. If you want the psql client
    locally, install it separately:
      brew install libpq           # client only
      brew install postgresql@18   # full server

    Docs: https://docs.pghardstorage.org
  EOS
end
